baseURL = "https://leportella-hugo-tutorial.netlify.app"
languageCode = "en-us"
title = "My New Hugo Site"

theme = "hugo-theme-codex" 

disqusShortname = "my-multilanguage-blog"


[params]
  twitter = "https://twitter.com/leportella"

[[menu.main]]
  identifier = "blog"
  name = "blog"
  title = "Blog"
  url = "/blog"
